"""
Agri-Advisor Advisory Synthesis Engine (Task T-18).
Fuses multi-agent specialist results, RAG grounded context, and weather risks into a cohesive,
eight-block farmer advisory with strict anti-hallucination grounding (BR-9) and disclaimer (BR-1/2).
"""

from __future__ import annotations

from collections import OrderedDict
from datetime import datetime, timezone
import json
import logging
from threading import Lock
import time
from typing import Any, Dict, List, Optional

from orchestrator.llm_client import LLMClient, llm_client as default_llm_client
from orchestrator.resilience import log_structured
from orchestrator.router import RoutingResult
from orchestrator.schemas import (
    CropAdviceResponse,
    DiseaseDiagnoseResponse,
    OrchestratorProcessRequest,
    OrchestratorProcessResponse,
    RagRetrieveResponse,
    ResponseMetadata,
    SourceItem,
    WeatherAdviceResponse,
    WeatherAlert,
)

logger = logging.getLogger("agri_advisor.synthesis")

# Rule BR-1 / BR-2: Standard Team-Agreed Advisory Disclaimer
ADVISORY_DISCLAIMER = (
    "This advisory is generated by an AI system to support your decision-making. "
    "It does not replace professional agricultural extension advice. "
    "For severe or uncertain cases, please consult your local Agriculture Extension Officer."
)

AGRICULTURE_HELPLINE = "1920 (Department of Agriculture Toll-Free)"


# ==============================================================================
# T-18.2 & T-18.6: Prompt Builder with Token Cost Optimization
# ==============================================================================

class PromptBuilder:
    """
    Constructs grounded, token-optimized prompts for LLM response synthesis.
    """

    SYSTEM_PROMPT = (
        "You are Agri-Advisor, an expert agricultural extension AI assistant developed for Sri Lankan farmers "
        "in collaboration with the Department of Agriculture (DOA).\n\n"
        "### CORE INSTRUCTIONS & GROUNDING RULES (Rule BR-9):\n"
        "1. STRICT GROUNDING: Use ONLY the verified specialist agent outputs and RAG context provided below. "
        "Do NOT invent unverified chemical names, dosage rates, or facts not present in the context.\n"
        "2. UNCERTAINTY: If information about a specific treatment or practice is missing from the context, state "
        "'I do not have sufficient verified information for this aspect; please consult your local extension officer.'\n"
        "3. FORMATTING: Structure your advisory strictly according to the Eight-Block Layout defined below.\n"
        "4. TONE: Clear, practical, farmer-friendly language. Avoid overly dense academic jargon.\n"
        "5. WEATHER-AWARE (Rule BR-12): If rain or high moisture is forecast, explicitly advise postponing chemical sprays."
    )

    @staticmethod
    def _format_compact_disease(disease_res: Optional[DiseaseDiagnoseResponse]) -> Optional[Dict[str, Any]]:
        if not disease_res:
            return None
        return {
            "disease": disease_res.disease,
            "confidence": f"{int(disease_res.confidence * 100)}%",
            "severity": disease_res.severity,
            "chemical_treatments": [
                f"{c.name} ({c.dosage}) - PHI: {c.pre_harvest_interval_days} days. {c.instructions}"
                for c in disease_res.treatment.chemical
            ],
            "organic_treatments": [
                f"{o.name} ({o.dosage}) - {o.instructions}"
                for o in disease_res.treatment.organic
            ],
            "cultural_treatments": [
                f"{cu.practice}: {cu.description}"
                for cu in disease_res.treatment.cultural
            ],
            "prevention": disease_res.prevention,
            "source": disease_res.source,
        }

    @staticmethod
    def _format_compact_weather(weather_res: Optional[WeatherAdviceResponse]) -> Optional[Dict[str, Any]]:
        if not weather_res:
            return None
        return {
            "condition": weather_res.current.condition,
            "temperature_c": weather_res.current.temperature_c,
            "humidity_pct": weather_res.current.humidity_pct,
            "rainfall_mm": weather_res.current.rainfall_mm,
            "disease_risk_level": weather_res.disease_risk.level,
            "disease_risk_factors": weather_res.disease_risk.contributing_factors,
            "advisory": weather_res.advisory,
            "alerts": [
                f"[{a.severity.upper()}] {a.title}: {a.recommended_action}"
                for a in weather_res.alerts
            ],
        }

    @staticmethod
    def _format_compact_crop(crop_res: Optional[CropAdviceResponse]) -> Optional[Dict[str, Any]]:
        if not crop_res:
            return None
        return {
            "crop": crop_res.crop,
            "season": crop_res.season,
            "zone": crop_res.agro_ecological_zone,
            "sections": crop_res.advisory_sections,
            "source": crop_res.source,
        }

    @classmethod
    def build_user_prompt(
        cls,
        request: OrchestratorProcessRequest,
        routing_res: RoutingResult,
    ) -> str:
        """
        Builds the synthesis prompt containing all agent data and RAG context (T-18.2, T-18.6).
        """
        compact_disease = cls._format_compact_disease(routing_res.disease_response)
        compact_weather = cls._format_compact_weather(routing_res.weather_response)
        compact_crop = cls._format_compact_crop(routing_res.crop_response)

        rag_context = ""
        if routing_res.rag_response and routing_res.rag_response.context:
            rag_context = routing_res.rag_response.context.strip()
        elif routing_res.rag_response and routing_res.rag_response.sources:
            rag_context = "\n\n".join(
                f"[{s.title} ({s.source})]: {s.content}"
                for s in routing_res.rag_response.sources
            )

        prompt_data = {
            "farmer_query": request.query,
            "language": request.language,
            "crop": routing_res.crop,
            "district": request.location.district,
            "agro_ecological_zone": request.location.agro_ecological_zone or "Dry Zone",
            "intent": routing_res.intent,
            "disease_findings": compact_disease,
            "weather_and_risks": compact_weather,
            "crop_cultivation_data": compact_crop,
            "verified_rag_corpus_context": rag_context or "No specific corpus passages retrieved.",
        }

        user_prompt = f"""FARMER QUERY & AGENT RESULTS:
```json
{json.dumps(prompt_data, indent=2, ensure_ascii=False)}
```

Synthesize a comprehensive, beautifully formatted Markdown advisory following the EXACT EIGHT-BLOCK LAYOUT below:

### REQUIRED EIGHT-BLOCK ADVISORY LAYOUT (Subtask T-18.3):
1. **Header**: `# 🌾 Advisory for <Crop> (<District>)` followed by a concise plain-language restatement.
2. **Diagnosis**: (If disease inquiry): State identified disease, scientific name, **Confidence: High/Medium/Low (<percentage>%)**, and **Severity: <Severity>**.
3. **Immediate Treatment**: Group into numbered/bulleted subheadings:
   - **Chemical Control**: Product name, dosage, instructions, and **Pre-Harvest Interval (PHI)** caution.
   - **Organic Treatment**: Botanical/organic formulation and method.
   - **Cultural Management**: Water/field management practices.
4. **Prevention**: Bulleted proactive cultural and seed prevention practices.
5. **Weather & Microclimate Advisory**: Current conditions, disease/pest risk warning, and spraying window guidance.
6. **Sources**: List cited Department of Agriculture/IRRI guide publications from the context.
7. **Disclaimer**: Exact text: "{ADVISORY_DISCLAIMER}"
8. **Follow-up & Helpline**: Short prompt inviting next question + "Helpline: {AGRICULTURE_HELPLINE}"

Ensure strict grounding in the provided context (BR-9)."""
        return user_prompt.strip()


# ==============================================================================
# T-18.7: Rule-Based Fallback Synthesis Engine (Rule FR-47)
# ==============================================================================

class RuleBasedFallbackSynthesizer:
    """
    Deterministically constructs contract-valid, eight-block advisories
    when LLM generation fails or is offline (Rule FR-47).
    """

    @classmethod
    def synthesize(
        cls,
        request: OrchestratorProcessRequest,
        routing_res: RoutingResult,
    ) -> str:
        """
        Generate complete 8-block advisory markdown without requiring an external LLM.
        """
        crop = routing_res.crop
        district = request.location.district
        disease_res = routing_res.disease_response
        weather_res = routing_res.weather_response
        crop_res = routing_res.crop_response
        rag_res = routing_res.rag_response

        blocks: List[str] = []

        # Block 1: Header
        blocks.append(
            f"# 🌾 Agricultural Advisory for {crop} ({district})\n"
            f"Based on verified Department of Agriculture (DOA) recommendations regarding your query: *\"{request.query}\"*."
        )

        # Block 2: Diagnosis
        if disease_res:
            conf_pct = int(disease_res.confidence * 100)
            conf_label = "High" if disease_res.confidence >= 0.80 else "Medium" if disease_res.confidence >= 0.60 else "Low"
            blocks.append(
                f"### 🔬 Disease Diagnosis\n"
                f"- **Identified Disease:** **{disease_res.disease}**\n"
                f"- **Confidence:** **{conf_label} ({conf_pct}%)**\n"
                f"- **Severity Level:** **{disease_res.severity}**\n"
                f"- **Confirmed Symptoms:** {', '.join(disease_res.symptoms_confirmed) if disease_res.symptoms_confirmed else 'Visual symptoms reported'}"
            )

        # Block 3: Immediate Treatment
        if disease_res and disease_res.treatment:
            chem_lines = []
            for c in disease_res.treatment.chemical:
                chem_lines.append(f"- **{c.name}**: {c.dosage} — *Instructions: {c.instructions}* (⚠️ **Pre-Harvest Interval (PHI): {c.pre_harvest_interval_days} days**)")
            
            org_lines = []
            for o in disease_res.treatment.organic:
                org_lines.append(f"- **{o.name}**: {o.dosage} — *{o.instructions}*")

            cul_lines = []
            for cu in disease_res.treatment.cultural:
                cul_lines.append(f"- **{cu.practice}**: {cu.description}")

            blocks.append(
                f"### 💊 Recommended Immediate Treatment Plan\n"
                f"#### 1. Chemical Control (Emergency Intervention):\n"
                f"{chr(10).join(chem_lines) if chem_lines else '- No synthetic chemical fungicide/bactericide required at this stage. (Pre-Harvest Interval (PHI): Observe standard 14-day pre-harvest safety interval if chemical intervention becomes necessary under extension officer guidance).'}\n\n"
                f"#### 2. Organic & Bio-Pesticide Control:\n"
                f"{chr(10).join(org_lines) if org_lines else '- Standard organic bio-fungicides.'}\n\n"
                f"#### 3. Cultural & Agronomic Field Practices:\n"
                f"{chr(10).join(cul_lines) if cul_lines else '- Maintain proper drainage and weed sanitation.'}"
            )
        elif crop_res:
            crop_lines = []
            for sec_name, sec_val in crop_res.advisory_sections.items():
                title = sec_name.replace("_", " ").title()
                crop_lines.append(f"- **{title}:** {sec_val}")
            blocks.append(
                f"### 🌱 Cultivation & Fertilizer Guidelines ({crop_res.season} Season)\n"
                f"**Agro-Ecological Zone:** {crop_res.agro_ecological_zone}\n\n"
                f"{chr(10).join(crop_lines)}"
            )

        # Block 4: Prevention
        if disease_res and disease_res.prevention:
            prev_lines = [f"- {p}" for p in disease_res.prevention]
            blocks.append(
                f"### 🛡️ Proactive Prevention & Crop Protection\n"
                f"{chr(10).join(prev_lines)}"
            )
        else:
            blocks.append(
                f"### 🛡️ Proactive Prevention & Best Practices\n"
                f"- Use certified disease-free seeds recommended by DOA research institutes.\n"
                f"- Follow balanced NPK fertilizer recommendations and avoid excessive nitrogen application.\n"
                f"- Inspect fields regularly and clear bunds of host weed species."
            )

        # Block 5: Weather Advisory
        if weather_res:
            alerts_text = ""
            if weather_res.alerts:
                alerts_text = f"\n> ⚠️ **Weather Alert ({weather_res.alerts[0].title})**: {weather_res.alerts[0].recommended_action}"

            blocks.append(
                f"### ⛅ Weather & Microclimate Risk Outlook\n"
                f"- **Current Weather ({district}):** {weather_res.current.condition}, {weather_res.current.temperature_c}°C, Humidity: {weather_res.current.humidity_pct}%\n"
                f"- **Fungal Disease Risk Level:** **{weather_res.disease_risk.level}** ({int(weather_res.disease_risk.score * 100)}% risk index)\n"
                f"- **Agronomic Weather Guidance:** {weather_res.advisory}{alerts_text}"
            )

        # Block 6: Sources
        sources_list: List[str] = []
        if rag_res and rag_res.sources:
            for s in rag_res.sources:
                sources_list.append(f"- *{s.title}* — {s.source or 'Department of Agriculture, Sri Lanka'}")
        if disease_res and disease_res.source:
            sources_list.append(f"- *{disease_res.source}*")
        if crop_res and crop_res.source:
            sources_list.append(f"- *{crop_res.source}*")

        unique_sources = list(dict.fromkeys(sources_list))
        blocks.append(
            f"### 📚 Verified Knowledge Sources\n"
            f"{chr(10).join(unique_sources) if unique_sources else '- Department of Agriculture (DOA) Sri Lanka Crop Handbook'}"
        )

        # Block 7: Disclaimer (Rule BR-1, BR-2)
        blocks.append(
            f"### ⚠️ Advisory Disclaimer\n"
            f"> {ADVISORY_DISCLAIMER}"
        )

        # Block 8: Follow-up & Helpline
        blocks.append(
            f"### 📞 Next Steps & Agricultural Extension Support\n"
            f"Feel free to ask a follow-up question regarding dosage, fertilizer timing, or alternative varieties.\n\n"
            f"**Extension Helpline:** {AGRICULTURE_HELPLINE}"
        )

        return "\n\n".join(blocks).strip()


class KeywordFallbackSynthesizer:
    """Return a minimal safe answer if both generated and rule-based synthesis fail."""

    @staticmethod
    def synthesize(request: OrchestratorProcessRequest) -> str:
        query = request.query.casefold()
        if any(word in query for word in ("rain", "weather", "forecast", "temperature")):
            guidance = (
                "I cannot retrieve current weather information right now. Please check an official "
                "weather update before spraying or making a weather-sensitive field decision."
            )
        elif any(word in query for word in ("spot", "wilt", "disease", "blast", "blight", "pest")):
            guidance = (
                "I cannot complete a reliable crop diagnosis right now. Avoid applying a chemical "
                "treatment until the problem is confirmed by an agricultural extension officer."
            )
        elif any(word in query for word in ("fertilizer", "fertiliser", "plant", "seed", "crop", "harvest")):
            guidance = (
                "I cannot prepare crop-specific growing guidance right now. Please follow current "
                "Department of Agriculture recommendations for your crop and season."
            )
        else:
            guidance = (
                "I cannot prepare a complete advisory right now. Please describe the crop and the "
                "problem you are seeing, or contact an agricultural extension officer."
            )
        return (
            f"### Advisory temporarily limited\n{guidance}\n\n"
            f"> {ADVISORY_DISCLAIMER}\n\n"
            f"Agriculture Extension Helpline: {AGRICULTURE_HELPLINE}"
        )


# ==============================================================================
# Response Synthesizer Coordinator
# ==============================================================================

class ResponseSynthesizer:
    """
    Coordinates LLM generation with automatic rule-based fallback.
    """

    def __init__(self, llm: Optional[LLMClient] = None) -> None:
        self.llm = llm or default_llm_client
        self.prompt_builder = PromptBuilder()
        self.fallback_synthesizer = RuleBasedFallbackSynthesizer()
        self.keyword_fallback = KeywordFallbackSynthesizer()
        self._answer_cache: OrderedDict[str, tuple[float, str]] = OrderedDict()
        self._cache_lock = Lock()
        self._cache_size = 128
        self._cache_ttl_seconds = 900

    @staticmethod
    def _append_status(
        answer: str,
        routing_res: RoutingResult,
        *,
        synthesis_mode: Optional[str] = None,
    ) -> str:
        notices: List[str] = []
        labels = {
            "disease_agent": "Disease diagnosis",
            "weather_agent": "Weather information",
            "crop_agent": "Crop cultivation advice",
            "rag_agent": "Verified knowledge lookup",
        }
        for agent_name, failure_mode in routing_res.agent_failures.items():
            label = labels.get(agent_name, "One advisory service")
            if agent_name == "weather_agent":
                notices.append(
                    "Current weather details are temporarily unavailable, so they are not included in this advisory."
                )
            elif agent_name == "rag_agent":
                notices.append(
                    "Verified knowledge lookup is temporarily unavailable; confirm recommendations with the Department of Agriculture."
                )
            else:
                state = "taking too long" if failure_mode == "timeout" else "temporarily unavailable"
                notices.append(f"{label} is {state}, so it is not included in this advisory.")

        if synthesis_mode == "cached":
            notices.append(
                "A recent saved advisory is being shown because the response service is unavailable. Check time-sensitive details, especially weather, before acting."
            )
        elif synthesis_mode == "rules":
            notices.append(
                "The response service is temporarily unavailable; this answer uses rule-based guidance."
            )
        elif synthesis_mode == "keywords":
            notices.append(
                "The full advisory could not be prepared, so only basic guidance is shown."
            )

        if not notices:
            return answer
        return f"{answer.rstrip()}\n\n### Service update\n" + "\n".join(f"- {notice}" for notice in notices)

    def _cached_answer(self, key: str) -> Optional[str]:
        with self._cache_lock:
            cached = self._answer_cache.get(key)
            if cached is None:
                return None
            cached_at, answer = cached
            if time.monotonic() - cached_at > self._cache_ttl_seconds:
                del self._answer_cache[key]
                return None
            if answer is not None:
                self._answer_cache.move_to_end(key)
            return answer

    def _remember_answer(self, key: str, answer: str) -> None:
        with self._cache_lock:
            self._answer_cache[key] = (time.monotonic(), answer)
            self._answer_cache.move_to_end(key)
            while len(self._answer_cache) > self._cache_size:
                self._answer_cache.popitem(last=False)

    def synthesize(
        self,
        request: OrchestratorProcessRequest,
        routing_res: RoutingResult,
    ) -> str:
        """
        Synthesize farmer advisory. Attempts LLM generation first,
        falling back to rule-based generation if LLM is unavailable or errors.
        """
        cache_key: Optional[str] = None
        llm_failed = not self.llm.is_available()
        try:
            user_prompt = self.prompt_builder.build_user_prompt(request, routing_res)
            cache_key = user_prompt
            if not llm_failed:
                generated_answer = self.llm.generate(
                    prompt=user_prompt,
                    system_prompt=self.prompt_builder.SYSTEM_PROMPT,
                    max_tokens=1200,
                    temperature=0.2,
                )
                if generated_answer and len(generated_answer.strip()) > 50:
                    answer = generated_answer.strip()
                    self._remember_answer(user_prompt, answer)
                    return self._append_status(answer, routing_res)
                llm_failed = True
                log_structured(
                    logger,
                    logging.ERROR,
                    "llm_synthesis_failed",
                    failure_mode="invalid_response",
                )
        except Exception as exc:
            llm_failed = True
            log_structured(
                logger,
                logging.ERROR,
                "llm_synthesis_failed",
                failure_mode="unavailable",
                exception_type=type(exc).__name__,
            )
        if llm_failed:
            log_structured(
                logger,
                logging.WARNING,
                "llm_synthesis_degraded",
                failure_mode="disabled" if not self.llm.is_available() else "unavailable",
            )

        if cache_key is not None:
            cached_answer = self._cached_answer(cache_key)
            if cached_answer:
                return self._append_status(cached_answer, routing_res, synthesis_mode="cached")

        try:
            answer = self.fallback_synthesizer.synthesize(request, routing_res)
            return self._append_status(answer, routing_res, synthesis_mode="rules")
        except Exception as exc:
            log_structured(
                logger,
                logging.ERROR,
                "rule_based_synthesis_failed",
                exception_type=type(exc).__name__,
            )
            answer = self.keyword_fallback.synthesize(request)
            return self._append_status(answer, routing_res, synthesis_mode="keywords")


# Global singleton instance
synthesizer = ResponseSynthesizer()
