"""
ui/config.py
Central configuration constants for the Agri-Advisor Streamlit frontend.
"""
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parents[1]
FIXTURE_DIR  = PROJECT_ROOT / "tests" / "fixtures"

# Path to the mock response used when the API is unreachable
FALLBACK_FIXTURE = FIXTURE_DIR / "orchestrator_process_response.json"

# ---------------------------------------------------------------------------
# API
# ---------------------------------------------------------------------------
API_BASE_URL       = "http://localhost:8000"
ORCHESTRATOR_PATH  = "/api/orchestrator/process"
ORCHESTRATOR_URL   = f"{API_BASE_URL}{ORCHESTRATOR_PATH}"
API_TIMEOUT_SEC    = 30  # seconds before we fall back to fixture data

# ---------------------------------------------------------------------------
# UI Copy
# ---------------------------------------------------------------------------
APP_TITLE    = "Agri-Advisor"
APP_SUBTITLE = "Smart Farming Assistant"
APP_ICON     = "🌾"

# ---------------------------------------------------------------------------
# Language options (display label → locale code)
# ---------------------------------------------------------------------------
LANGUAGES: dict[str, str] = {
    "English": "en",
    "සිංහල (Sinhala)": "si",
    "தமிழ் (Tamil)": "ta",
}

# ---------------------------------------------------------------------------
# Sri Lanka districts (alphabetical)
# ---------------------------------------------------------------------------
DISTRICTS: list[str] = [
    "Ampara", "Anuradhapura", "Badulla", "Batticaloa", "Colombo",
    "Galle", "Gampaha", "Hambantota", "Jaffna", "Kalutara",
    "Kandy", "Kegalle", "Kilinochchi", "Kurunegala", "Mannar",
    "Matale", "Matara", "Monaragala", "Mullaitivu", "Nuwara Eliya",
    "Polonnaruwa", "Puttalam", "Ratnapura", "Trincomalee", "Vavuniya",
]

# ---------------------------------------------------------------------------
# Common crop contexts (optional)
# ---------------------------------------------------------------------------
CROP_CONTEXTS: list[str] = [
    "— Not specified —",
    "Paddy (Rice)",
    "Maize",
    "Banana",
    "Coconut",
    "Tea",
    "Rubber",
    "Vegetables (Mixed)",
    "Tomato",
    "Chilli",
    "Brinjal",
    "Beans",
    "Onion",
    "Mango",
    "Pineapple",
    "Other",
]

# ---------------------------------------------------------------------------
# Weather severity → badge colour mapping
# ---------------------------------------------------------------------------
SEVERITY_STYLE: dict[str, dict] = {
    "none":     {"color": "#6B7280", "bg": "#F3F4F6", "label": "No Alert",  "bold": False},
    "low":      {"color": "#166534", "bg": "#DCFCE7", "label": "Low",       "bold": False},
    "moderate": {"color": "#92400E", "bg": "#FEF3C7", "label": "Moderate",  "bold": False},
    "high":     {"color": "#9A3412", "bg": "#FED7AA", "label": "High",      "bold": True},
    "severe":   {"color": "#FFFFFF", "bg": "#DC2626", "label": "Severe ⚠️", "bold": True},
}

# ---------------------------------------------------------------------------
# Disclaimer (Block 7) – static, team-agreed wording
# ---------------------------------------------------------------------------
DISCLAIMER_EN = (
    "This advisory is generated by an AI system to support your decision-making. "
    "It does not replace professional agricultural extension advice. "
    "For severe or uncertain cases, please consult your local Agriculture Extension Officer."
)
DISCLAIMER_SI = (
    "මෙම උපදේශය ඔබේ තීරණ ගැනීම සඳහා සහාය වීමට AI පද්ධතියක් විසින් ජනනය කරන ලදී. "
    "එය වෘත්තීය කෘෂිකර්ම දිගහැරීමේ උපදේශය ප්‍රතිස්ථාපනය නොකරයි. "
    "දරුණු හෝ අවිනිශ්චිත අවස්ථාවන්හිදී, කරුණාකර ඔබේ දේශීය කෘෂිකර්ම දිගහැරීමේ නිලධාරියා හමුවන්න."
)
DISCLAIMER_TA = (
    "இந்த ஆலோசனை உங்கள் முடிவெடுப்பதை ஆதரிக்க AI அமைப்பால் உருவாக்கப்பட்டது. "
    "இது தொழில்முறை வேளாண் விரிவாக்க ஆலோசனையை மாற்றாது. "
    "கடுமையான அல்லது நிச்சயமற்ற சந்தர்ப்பங்களில், உங்கள் உள்ளூர் வேளாண் விரிவாக்க அதிகாரியை அணுகவும்."
)
DISCLAIMERS = {"en": DISCLAIMER_EN, "si": DISCLAIMER_SI, "ta": DISCLAIMER_TA}

# Helpline placeholder
HELPLINE_TEXT = "☎ Agriculture Extension Office: 1920  |  🌐 doa.gov.lk"
